In [6]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
file = pd.read_csv("mlproject.csv")

In [ ]:
file.dtypes

Station Number           int64
State                   object
Temp Min               float64
Temp Max               float64
DO Min                 float64
DO Max                 float64
pH Min                 float64
pH Max                 float64
Conductivity Min       float64
Conductivity Max       float64
BOD Min                float64
BOD Max                float64
Nitrate Min            float64
Nitrate Max            float64
Faecal Coliform Min      int64
Faecal Coliform Max      int64
Total Coliform Min     float64
Total Coliform Max       int64
dtype: object

In [8]:
file

     Station Number               State  ...  Total Coliform Min  Total Coliform Max
0              1867  HIMACHAL\n PRADESH  ...                20.0                  20
1              2611  HIMACHAL\n PRADESH  ...                20.0                  20
2              1389  HIMACHAL\n PRADESH  ...                20.0                  20
3              1086  HIMACHAL\n PRADESH  ...                21.0                  21
4              1087  HIMACHAL\n PRADESH  ...                25.0                  25
..              ...                 ...  ...                 ...                 ...
385            3024          TAMIL NADU  ...              1200.0                1700
386            1641              ODISHA  ...                10.0                 200
387            2397           JHARKHAND  ...              2200.0             3500000
388            1641              ODISHA  ...               330.0               54000
389            2397           JHARKHAND  ...               930.0                1500

[390 rows x 18 columns]

In [9]:
import numpy as np

In [10]:
file_proc = file.drop(['Conductivity Min','Conductivity Max','Total Coliform Min','Total Coliform Max'],axis= 1)

In [11]:
file_proc

     Station Number  ... Faecal Coliform Max
0              1867  ...                   2
1              2611  ...                   2
2              1389  ...                   2
3              1086  ...                   2
4              1087  ...                   2
..              ...  ...                 ...
385            3024  ...             2200000
386            1641  ...               16000
387            2397  ...                 230
388            1641  ...               16000
389            2397  ...                 230

[390 rows x 14 columns]

In [12]:
# duplicate
duplicateRowsDF = file_proc[file_proc.duplicated()]
duplicateRowsDF

     Station Number      State  ...  Faecal Coliform Min  Faecal Coliform Max
388            1641     ODISHA  ...                  130                16000
389            2397  JHARKHAND  ...                  150                  230

[2 rows x 14 columns]

In [13]:
file_proc.shape

(390, 14)

In [14]:
file_proc.iloc[:,2:14]

     Temp Min  Temp Max  ...  Faecal Coliform Min  Faecal Coliform Max
0         9.0      12.0  ...                    2                    2
1         9.0      12.0  ...                    2                    2
2        12.0      17.0  ...                    2                    2
3        14.0      17.0  ...                    2                    2
4        14.0      17.0  ...                    2                    2
..        ...       ...  ...                  ...                  ...
385      25.0      32.0  ...                  630              2200000
386      15.0      32.0  ...                  130                16000
387      22.5      29.0  ...                  150                  230
388      15.0      32.0  ...                  130                16000
389      22.5      29.0  ...                  150                  230

[390 rows x 12 columns]

In [15]:
data = np.array(file_proc.iloc[:,2:14])

In [16]:
data

array([[9.00e+00, 1.20e+01, 9.70e+00, ..., 2.00e-01, 2.00e+00, 2.00e+00],
       [9.00e+00, 1.20e+01, 9.70e+00, ..., 5.00e-01, 2.00e+00, 2.00e+00],
       [1.20e+01, 1.70e+01, 9.10e+00, ..., 4.00e-01, 2.00e+00, 2.00e+00],
       ...,
       [2.25e+01, 2.90e+01, 7.50e+00, ..., 1.00e+00, 1.50e+02, 2.30e+02],
       [1.50e+01, 3.20e+01, 6.40e+00, ..., 7.30e+00, 1.30e+02, 1.60e+04],
       [2.25e+01, 2.90e+01, 7.50e+00, ..., 1.00e+00, 1.50e+02, 2.30e+02]])

In [17]:
data.shape

(390, 12)

In [18]:
final_col_list = []
for i in range(0,12,2):
    col_mean = (data[:,i] + data[:,i+1])/2
    final_col_list.append(col_mean)

# transpose this
tmp_arr = np.array(final_col_list)

In [19]:
# convert this to pandas dataframe
tmp_arr.T

array([[1.050e+01, 9.900e+00, 7.400e+00, 1.500e-01, 2.000e-01, 2.000e+00],
       [1.050e+01, 9.900e+00, 7.300e+00, 3.000e-01, 3.500e-01, 2.000e+00],
       [1.450e+01, 9.350e+00, 7.450e+00, 3.000e-01, 3.000e-01, 2.000e+00],
       ...,
       [2.575e+01, 8.050e+00, 7.450e+00, 1.650e+00, 5.500e-01, 1.900e+02],
       [2.350e+01, 7.300e+00, 7.900e+00, 1.200e+00, 3.750e+00, 8.065e+03],
       [2.575e+01, 8.050e+00, 7.450e+00, 1.650e+00, 5.500e-01, 1.900e+02]])

In [20]:
# final_preprocessed data
final_df = pd.DataFrame(tmp_arr.T,columns = ['Temp','DO','pH','BOD','Nitrate','Faecal Coliform'])
final_df

      Temp    DO     pH    BOD  Nitrate  Faecal Coliform
0    10.50  9.90  7.400   0.15   0.2000              2.0
1    10.50  9.90  7.300   0.30   0.3500              2.0
2    14.50  9.35  7.450   0.30   0.3000              2.0
3    15.50  9.30  7.475   0.25   0.2700              2.0
4    15.50  8.95  7.475   0.15   0.3565              2.0
..     ...   ...    ...    ...      ...              ...
385  28.50  1.30  7.450  40.10   1.5000        1100315.0
386  23.50  7.30  7.900   1.20   3.7500           8065.0
387  25.75  8.05  7.450   1.65   0.5500            190.0
388  23.50  7.30  7.900   1.20   3.7500           8065.0
389  25.75  8.05  7.450   1.65   0.5500            190.0

[390 rows x 6 columns]

In [21]:
print(max(final_df['Nitrate']))
print(max(final_df['Temp']))
print(max(final_df['DO']))
print(max(final_df['pH']))
print(max(final_df['BOD']))
print(max(final_df['Faecal Coliform']))

442.35
33.5
9.899999999999999
8.55
132.0
4600200.0

## Initial Weights as in paper
- Temp - 0.10
- DO - 0.17
- pH - 0.11
- BOD - 0.11
- Nitrate - 0.10
- Faecal Coliform - 0.16

## Initial weights adjusted
- Temp - 0.1333333333333333
- DO - 0.2266666666666667
- pH - 0.1466666666666667
- BOD - 0.1466666666666667
- Nitrate - 0.1333333333333333
- Faecal Coliform - 0.2133333333333333

Water Quality Index

	WQI is computed for each factor as the product of Q-value and weighting factor. 

WQI = Q-value x Weighting factor

The overall WQI is the weighted average of all Q-values:

Overall WQI = (Q-value x Weighting factor) / Weighting factors

In [22]:
from sklearn import preprocessing

In [23]:
df_arr = final_df.values
# performing zero to one normalization
zero_to_one = preprocessing.MinMaxScaler()
zero_to_one.fit(df_arr)
scaled = zero_to_one.transform(df_arr) * 100
scaled

array([[3.13432836e+01, 1.00000000e+02, 4.88888889e+01, 1.13636364e-01,
        4.52130666e-02, 4.34763706e-05],
       [3.13432836e+01, 1.00000000e+02, 4.44444444e+01, 2.27272727e-01,
        7.91228665e-02, 4.34763706e-05],
       [4.32835821e+01, 9.43298969e+01, 5.11111111e+01, 2.27272727e-01,
        6.78195999e-02, 4.34763706e-05],
       ...,
       [7.68656716e+01, 8.09278351e+01, 5.11111111e+01, 1.25000000e+00,
        1.24335933e-01, 4.13025521e-03],
       [7.01492537e+01, 7.31958763e+01, 7.11111111e+01, 9.09090909e-01,
        8.47744998e-01, 1.75318464e-01],
       [7.68656716e+01, 8.09278351e+01, 5.11111111e+01, 1.25000000e+00,
        1.24335933e-01, 4.13025521e-03]])

In [24]:
r = pd.DataFrame(scaled)
c = 0
for i in r.iloc[:,4]:
  if i > 4:
    c+=1
print(c)
# count(pd.iloc[:,4])

3

In [25]:
max(r.iloc[:,4])

100.0

In [26]:
scaled.shape

(390, 6)

In [27]:
# Initial factor values for each factor
weight_factor = np.array([0.1333333333333333,0.2266666666666667,0.1466666666666667,0.1466666666666667,0.1333333333333333,0.2133333333333333]).reshape(6,1)

In [28]:
final_df['WQI'] = np.dot(scaled,weight_factor)/np.sum(weight_factor)

In [29]:
pd.set_option('display.max_rows', final_df.shape[0]+1)
print(final_df)

      Temp    DO     pH      BOD   Nitrate  Faecal Coliform        WQI
0    10.50  9.90  7.400    0.150    0.2000              2.0  34.038846
1    10.50  9.90  7.300    0.300    0.3500              2.0  33.408182
2    14.50  9.35  7.450    0.300    0.3000              2.0  34.691269
3    15.50  9.30  7.475    0.250    0.2700              2.0  35.128944
4    15.50  8.95  7.475    0.150    0.3565              2.0  34.302570
5    17.00  8.75  7.395    1.050    0.2825              2.0  34.008519
6    17.00  8.85  7.835    0.100    0.5310             18.0  37.012354
7    15.00  8.25  7.955    0.150    0.5655             32.0  35.603154
8    12.50  7.15  7.710    0.650    0.2800             13.5  30.487510
9    21.00  7.40  7.600    2.000    0.7000            515.0  33.902735
10   21.00  7.70  7.930    1.000    0.6000            285.0  36.639685
11   25.50  6.55  7.450    1.500    0.8000           1050.0  32.679688
12   25.50  3.55  7.380   69.000    7.8000         113500.0  33.445561
13   24.00  4.95  7.725   21.000    2.0000          38000.0  32.510626
14   20.50  2.10  7.200   15.000    1.7000           1325.0  20.189786
15   23.00  7.50  7.800    1.100    0.6000            645.0  36.133725
16   23.50  7.35  7.650    1.150    0.8000            750.0  35.016507
17   20.50  5.20  7.100    3.050    1.9000            575.0  25.456693
18   23.50  7.60  8.050    0.750    1.0000            425.0  38.168184
19   15.50  8.90  7.700    0.300    0.4000              0.0  35.670367
20   12.50  9.15  7.650    0.350    0.3500              2.0  34.738662
21   11.70  9.15  7.750    0.150    0.3000              4.0  35.048385
22   21.50  7.75  7.950    0.500    0.5000            480.0  37.028234
23   20.00  7.45  7.750    2.000    0.5000            950.0  34.595330
24   22.00  8.00  7.550    2.100    0.4500            265.0  35.379297
25   22.00  8.15  7.450    2.200    2.7500            230.0  35.158236
26   19.50  7.80  7.250    2.850    0.4500            245.0  32.044604
27   20.00  8.05  7.400    2.850    0.3500            175.0  33.802240
28   21.50  7.80  7.300    2.700    0.4000            285.0  33.148561
29   22.50  7.70  7.400    2.600    0.3500            190.0  33.951687
30   25.00  8.25  7.750    3.500    0.3000           2900.0  38.624477
31   25.00  8.30  8.050    4.000    0.3000           3600.0  40.755673
32   24.00  8.70  8.050    3.100    0.3000           3150.0  41.190284
33   24.50  8.55  7.950    3.400    0.3000           3400.0  40.421415
34   26.00  8.30  7.850    3.300    0.3000           3550.0  39.771970
35   26.00  7.65  7.850    3.450    0.3000           4450.0  38.273910
36   23.50  7.90  7.900    4.750    1.1000          23000.0  38.443587
37   21.20  8.15  6.950    2.500    0.3500           1250.0  31.546292
38   21.25  8.00  7.200    2.750    0.4500           2000.0  32.879577
39   16.75  8.15  8.200    3.050    0.3000           1750.0  37.985219
40   25.75  7.05  8.450    5.700    0.3500          36000.0  41.081276
41   26.50  7.10  8.450    4.900    0.3500          25000.0  41.356721
42   25.50  7.80  7.850    4.250    0.7000         167000.0  39.280188
43   26.00  7.55  7.750    3.150    0.9000         120000.0  37.908994
44   26.50  7.05  7.850    3.250    0.8000         180000.0  37.877811
45   26.50  6.40  7.900    3.000    0.6500         150000.0  36.513413
46   24.50  6.65  7.900    3.900    0.7000         195000.0  36.611780
47   27.00  6.00  7.700    3.450    0.5000         261500.0  35.036564
48    0.00  5.65  7.800   28.000    0.0600           2366.5  25.637067
49    0.00  6.60  7.450    4.000    0.8300          17022.5  23.000027
50   25.30  7.75  7.600    4.000    0.0000          27070.0  36.756319
51    0.00  1.50  7.800   31.500    0.5650        4600200.0  37.665942
52    0.00  5.85  7.850   10.500    0.8650          66100.0  24.805730
53   19.00  7.60  7.750   10.000    1.8250          55225.0  35.728362
54   23.00  4.25  7.750   12.000    5.4050        1750200.0  37.682766
55   24.00  7.10  8.000   17.000   11.8950           6565.0  39.035305
56   25.00  7.70  8.100   21.000    6.0350          12004.0  41.780264
57   24.00  8.00  7.900    9.000    1.6300          35010.0  39.420162
58   23.90  8.50  7.900    2.150    1.1100           6000.0  39.637428
59   24.50  7.95  7.900    5.900    0.3500           3650.0  38.973871
60   26.50  8.00  8.200    3.350    0.3000           1400.0  41.547010
61   26.75  2.25  8.550   33.800    0.5500         165000.0  34.641129
62   23.00  7.80  7.650    3.200    0.3000           2200.0  36.088480
63   26.25  7.85  8.300    3.850    0.3000           9000.0  41.839645
64   25.15  9.00  8.200    2.200    0.9000            225.0  43.231325
65   25.55  7.40  8.050    3.550    1.5500           2300.0  38.853135
66   27.15  2.20  7.500   10.500    1.6500         112000.0  25.037531
67   26.25  7.40  8.450    4.750    0.3000          17000.0  41.902976
68   26.25  7.90  8.350    3.950    0.3000          10500.0  42.300476
69   25.25  8.40  8.100    2.250    0.9000            310.0  41.223162
70   25.35  8.40  8.150    2.350    0.9000            385.0  41.600348
71   25.05  8.35  8.200    2.750    0.9500           1095.0  41.739277
72   25.20  8.15  7.950    2.850    1.0000           1495.0  39.716468
73   25.55  7.35  8.050    3.550    1.2000           2300.0  38.725747
74   25.80  6.85  7.950    3.600    1.2500           3150.0  37.016017
75   25.95  2.85  7.700    8.800    1.4500          14950.0  26.737538
76   25.80  2.60  7.650   11.900    1.5500          18500.0  26.131640
77   27.00  2.35  7.550    9.700    1.5500          71500.0  25.374550
78   27.15  2.15  7.450   10.500    1.6500         109500.0  24.583173
79   27.60  4.20  7.950    6.050    0.9000          15800.0  31.860331
80   27.80  5.10  7.950    5.800    1.0500          14650.0  34.014437
81   23.50  6.75  7.850    4.550    0.8000           5150.0  35.316332
82   24.00  6.55  7.850    4.650    0.8500           5500.0  35.062224
83   26.50  8.15  8.200    3.250    0.3000           2300.0  41.890588
84   23.00  7.55  7.700    3.800    0.5500           9350.0  35.937573
85   22.50  7.90  7.850    3.450    0.3500           6625.0  37.476661
86   22.00  8.50  7.800    3.600    0.8000           5250.0  38.377646
87   23.00  7.70  7.850    3.250    0.3000           6625.0  37.184583
88   23.00  7.55  7.800    3.500    0.4500           6050.0  36.537774
89   23.85  7.45  7.700    1.500    0.3000           1090.0  35.740808
90   24.15  7.85  7.600    1.550    0.3000           1240.0  36.149318
91   21.50  6.55  7.350    1.700    1.0000            605.0  30.461983
92   21.50  6.55  7.350    1.950    1.1000           1550.0  30.497157
93   22.00  6.40  7.200    2.000    1.0500           1200.0  29.370294
94   24.00  6.90  7.100    3.500    1.3500           1230.0  30.858696
95   25.00  7.00  7.350    1.700    1.6500           3900.0  32.941437
96   27.00  6.90  7.250    1.700    0.7500           1230.0  32.812418
97   25.50  5.90  7.550    1.900    1.5500           1180.0  31.880293
98   26.50  6.85  7.200    1.700    1.1000            650.0  32.178509
99   27.00  7.15  7.350    2.300    0.7500            605.0  34.112231
100  27.00  7.75  7.100    1.800    1.3000           2115.0  33.852688
101  22.50  7.80  7.400    2.400    1.9500            545.0  34.213016
102  25.00  6.55  7.150    3.300    0.8500            900.0  30.725939
103  23.00  7.00  7.350    3.100    2.0000           1500.0  32.300392
104  27.00  6.85  7.000    3.050    1.1500           2050.0  31.231810
105  23.50  7.80  7.050    1.850    0.7000            635.0  32.231173
106  22.50  6.25  7.150    1.650    1.1500            515.0  28.853807
107  22.50  5.20  7.450    2.300    1.1000           1550.0  28.431269
108  22.50  7.60  7.000    2.800    1.3000           1150.0  31.165912
109  23.00  6.70  6.900    2.700    1.3000           1500.0  28.600484
110  30.00  5.95  7.650    2.900    0.9500           1900.0  34.536393
111  22.00  7.85  6.900    4.350    1.6000           1930.0  31.084130
112  20.00  6.80  7.000    1.850    1.2000            515.0  28.189957
113  28.00  4.35  6.750    2.300    0.6500           1300.0  24.056383
114  27.00  6.50  7.050    2.100    1.9500           1550.0  30.656105
115  28.50  6.90  7.700    1.250    1.3000            900.0  36.307814
116  23.00  7.40  7.400    1.600    2.5000           1150.0  33.407807
117  23.00  6.95  7.000    1.500    1.4500           1150.0  29.706093
118  23.00  5.75  7.000    1.750    0.9500           1200.0  26.914908
119  25.50  6.60  7.000    2.600    0.8500           2350.0  29.992951
120  25.50  4.75  6.900    3.300    1.4000           1150.0  25.106866
121  25.50  3.65  7.000   24.000    4.1000         121350.0  26.127080
122  26.00  3.10  8.100    4.750    1.2000           1900.0  29.430984
123  24.00  8.00  6.900    2.000    1.8000            700.0  31.969878
124  25.50  5.70  6.800    1.750    1.9000            545.0  26.514988
125  24.50  5.80  6.850    1.750    1.4000           1500.0  26.665939
126  27.00  9.30  6.750    2.600    0.9000           1900.0  35.269035
127  24.50  7.35  7.150    2.150    1.0500            545.0  32.272954
128  28.00  5.05  6.300    3.250    0.8500            850.0  22.868286
129  27.00  5.85  7.350    1.300    2.6500            600.0  31.020566
130  28.00  5.40  6.800    1.750    1.3500            700.0  26.793123
131  24.50  5.70  6.950    1.950    0.8000           1550.0  27.088483
132  24.00  5.65  7.000    1.850    0.8000            605.0  27.083072
133  24.00  5.10  6.950    1.900    2.1000            700.0  25.517103
134  24.00  6.10  7.200    2.550    0.5500           3950.0  29.524077
135  17.50  7.75  7.000    1.450    0.5000             22.0  29.347033
136  18.00  7.70  7.050    1.400    0.2500             18.5  29.742018
137  24.50  7.45  7.400    1.850    0.4000             30.0  34.080946
138  23.50  7.15  7.750    1.800    0.6000             26.5  35.263844
139  23.50  7.10  7.700    1.300    0.5000             22.0  34.762489
140  26.50  5.10  7.850    1.600    2.0500             21.5  32.340808
141  26.00  7.60  8.295    0.640    0.6500             18.5  40.735589
142  31.00  7.70  8.100    0.550    0.3500              2.0  41.669085
143  31.00  7.35  8.300    1.400    0.5000             15.0  42.253945
144  31.50  7.10  8.250    0.900    0.5500             15.0  41.488784
145  28.50  8.05  8.100    1.200    0.4500             16.0  41.567231
146  27.50  6.40  8.050    1.100    0.5000             12.5  36.978005
147  28.00  7.60  8.360    1.415    0.4850             22.0  42.036466
148  25.50  7.20  8.100    1.550    1.1000              2.0  38.445363
149  26.50  5.60  8.050    1.450    0.5000             12.5  34.749468
150  25.00  7.10  7.800    2.000    2.0000             17.0  36.134323
151  27.00  6.90  7.800    2.100    1.9000              8.0  36.471044
152  26.00  7.20  7.600    1.650    1.5500              6.0  35.409802
153  26.00  7.00  7.700    2.000    1.8000             28.0  35.640827
154  22.00  6.70  7.950    1.800    0.6500              6.5  34.920400
155  24.00  6.90  8.250    1.550  442.3500              2.0  51.425272
156  27.00  6.55  7.750    2.850    0.3000             12.5  35.362376
157  26.00  5.95  8.250    3.500    0.0500             24.5  36.886306
158  31.00  2.45  7.650   65.500    0.2000           1105.0  33.684971
159  27.00  5.50  8.000   12.400    1.0500             69.5  35.622379
160  27.50  5.45  7.950    4.850    0.1500             74.5  34.512626
161  28.00  3.20  8.500   37.500    0.2500            866.5  36.673549
162  30.00  6.70  8.150    4.000    0.0500             17.0  39.634592
163  30.50  5.50  7.900    2.400    0.3500             23.5  35.231138
164  27.00  4.65  7.750    2.700    0.3500             10.5  30.907344
165  29.50  2.95  7.650  132.000    0.2000           4150.0  41.659351
166  31.00  7.00  8.150    1.150    0.4000             12.5  40.427495
167  20.20  7.60  7.850    1.450    1.4000              6.0  35.638939
168  23.50  8.10  8.055    1.950    0.8750              2.0  39.496765
169  19.50  7.55  7.950    1.300    0.8000              8.0  35.860602
170  23.50  8.25  8.000    1.900    1.5000              3.0  39.502050
171  24.50  7.95  8.050    2.050    3.0500              2.0  39.588337
172  16.00  6.95  7.700    1.700    0.8000              6.5  31.480314
173  19.50  7.50  7.900    1.450    2.2500              6.0  35.478201
174  20.40  7.55  7.950    1.350    0.7500              6.5  36.222853
175  19.00  7.75  7.850    1.000    2.4500             13.5  35.493526
176  19.75  7.35  7.900    1.600    2.6000             15.0  35.254447
177  26.00  7.55  8.100    1.400    0.8000              2.0  39.436528
178  26.50  7.50  8.100    1.400    0.9500              2.0  39.523216
179  25.00  7.25  7.700    1.100    0.6000              2.0  35.690718
180  26.00  7.60  7.600    1.400    0.5000              5.0  36.285079
181  27.60  8.00  7.800    1.250    0.8000              7.0  39.152692
182  24.50  8.00  8.000    1.950    1.9500              6.0  39.335001
183  26.50  7.20  7.900    1.400    0.8000              2.0  37.513960
184  26.50  7.30  7.550    1.150    0.5000              3.0  35.429340
185  27.25  7.40  8.100    1.550    1.1000              2.0  39.609234
186  29.50  7.25  7.700    1.000    0.4500            120.0  37.466678
187  30.50  7.35  7.850    0.950    0.2000             15.5  39.062567
188  26.50  7.30  8.050    0.650    0.5000              9.0  38.633071
189  29.50  7.05  7.850    0.950    0.5000             18.0  37.972580
190  25.00  7.00  8.300    1.450    1.1000              2.0  39.071597
191  20.10  6.75  7.850    1.600    0.7000             61.0  33.608706
192  23.00  6.45  7.800    2.050    1.0000              3.0  33.794751
193  11.50  8.65  7.850    1.450    1.3000             20.5  34.626913
194  20.00  5.75  7.700    1.600    1.0000              7.0  30.263149
195  24.50  4.35  7.700    5.500    0.1000             16.0  29.188964
196  23.00  4.85  7.800    5.200    0.2500             12.0  30.383355
197  30.00  4.45  7.850    1.350    0.3000             57.5  32.134583
198  30.50  6.85  7.700    1.100    0.2000             37.5  36.933173
199  29.00  6.95  7.800    1.650    0.1000            302.5  37.281013
200  30.00  6.95  7.300    1.100    0.2000             26.5  34.360386
201  29.00  5.35  7.550    2.300    0.1000            323.0  31.984869
202  26.50  7.15  8.100    3.000    2.8000              9.5  38.938922
203  25.75  7.25  7.950    2.000    2.3000              2.0  37.770097
204  27.00  7.65  7.950    0.900    2.6000           1201.0  39.094698
205  26.00  6.85  7.750    1.000    1.6500           8022.5  35.537679
206  26.50  6.85  7.800    2.200    1.6000          12550.0  36.215432
207  27.00  7.55  7.900    1.100    0.7500           1751.0  38.504105
208  27.50  7.90  7.850    0.750    0.9000            551.0  39.155121
209  27.50  7.25  7.900    1.050    1.3000           2451.0  38.016348
210  26.50  7.95  8.000    0.750    1.9000           1210.0  39.884925
211  27.00  7.45  7.850    0.750    2.2000            660.0  37.944260
212  29.00  7.50  7.900    0.800    1.0000            466.0  39.151529
213  29.00  7.05  7.850    1.400    2.0000          80065.0  38.240005
214  27.00  6.65  7.700    1.300    1.3500           8001.0  35.166600
215  26.00  7.05  8.050    0.850    1.4000            396.0  37.901019
216  28.75  7.80  7.850    0.700    1.7000            872.5  39.439005
217  27.00  7.45  7.800    1.000    1.0500            551.0  37.610943
218  28.50  6.75  7.950    0.650    1.2000            246.0  37.514215
219  29.00  7.80  7.900    1.000    2.4000           8022.5  39.952025
220  26.00  6.50  7.800    1.450    3.2000           2710.0  35.117819
221  23.50  7.60  7.700    1.100    1.3500           2710.0  35.946738
222  24.00  5.80  7.850    1.300    1.3500            689.0  32.930185
223  23.50  7.20  7.900    1.700    1.1500           4601.0  36.385141
224  24.00  7.00  7.800    1.850    0.9500            551.0  35.456797
225  29.00  7.25  8.050    1.650    0.9500          80245.0  40.008026
226  30.00  5.35  7.700    5.700    4.7500          83950.0  34.266413
227  29.00  6.55  8.050    0.650    0.5500           4710.0  37.898827
228  27.50  7.45  7.700    3.350    3.9000          80090.0  37.873972
229  26.50  7.35  7.650    1.250    0.6000           8001.0  36.249246
230  28.00  7.05  7.900    0.950    1.1500            701.0  37.724251
231  28.75  7.30  7.750    0.850    2.7500          46001.0  37.876367
232  25.50  7.00  7.850    2.500    4.2000          80039.0  36.918545
233  30.00  7.60  7.850    1.550    1.2000           2810.0  39.557522
234  29.50  6.45  8.000    1.050    1.1500            396.0  37.580752
235  29.00  8.30  7.850    0.950    1.1000           1060.0  40.717455
236  28.00  5.90  7.750    6.200    1.9000           8510.0  34.701342
237  26.00  7.60  7.900    1.700    1.9500           8001.0  38.354755
238  27.50  6.75  8.050    1.100    2.1500           8745.0  37.886105
239  28.65  6.25  7.750    2.400    2.2500          11395.0  35.379624
240  26.00  4.40  7.500   14.050    7.5500          84600.0  30.165928
241  27.10  2.20  7.500   21.450    4.9500          86500.0  26.215510
242  27.50  1.30  7.700   20.450    7.1000         160000.0  25.869874
243  30.00  1.75  7.450    9.050    7.3000         297000.0  25.661512
244  27.50  4.55  7.900    1.300    0.8000           8115.0  31.746043
245  27.00  6.20  7.900    1.500    1.2500           8395.0  35.439793
246  27.25  4.50  7.750    1.100    1.1500            701.0  30.505869
247  28.50  6.10  8.000    1.150    0.9500           4639.0  36.389633
248  31.10  6.50  7.850    1.050    2.3000          12075.0  37.445454
249  30.50  5.75  7.900    1.300    1.2000           8665.0  35.758804
250  27.00  5.80  8.050    1.100    0.5000           8165.0  35.414745
251  27.85  5.80  8.150    3.650    1.2000          27001.0  36.796690
252  27.70  9.25  8.150    1.150    1.7000           8165.0  44.448785
253  26.75  6.35  7.950    1.250    0.7500          27039.0  36.060344
254  24.50  6.35  7.800    1.800    1.4000           6501.0  34.172503
255  27.25  5.65  7.950    1.950    0.8000           4634.0  34.598992
256  29.00  6.05  7.850    1.950    1.5500          46700.0  35.796052
257  27.00  5.75  7.950    1.800    0.8500           8534.0  34.736093
258  25.75  5.95  8.000    2.800    1.5000           8501.0  35.162411
259  24.00  7.30  8.000    1.200    0.3500          46110.0  37.582503
260  22.50  7.55  7.950    1.150    1.1000           8001.0  37.084076
261  23.50  7.45  7.550    1.250    1.2500           2701.0  34.632055
262  22.50  6.75  8.050    1.400    0.6000           2701.0  35.854640
263  22.50  7.20  8.100    1.200    0.6000           4622.5  37.218801
264  23.00  6.05  7.950    1.100    2.7500          46245.0  33.999461
265  26.00  7.25  7.900    1.050    1.4000           8110.0  37.448591
266  26.50  6.95  7.700    1.650    1.2000           8135.0  35.703615
267  25.50  7.60  8.050    0.800    1.0500           2755.0  38.982072
268  27.00  7.85  7.750    1.050    1.4500           8225.0  38.272925
269  25.50  7.15  8.200    1.050    1.3315           1751.0  38.939910
270  25.50  7.60  7.950    1.750    0.9695          12085.0  38.476617
271  26.50  6.95  8.000    1.000    2.4000           1201.0  37.590963
272  25.50  7.85  7.950    0.850    1.2000           1255.0  38.917533
273  25.50  6.60  7.650    2.000    1.7000           8001.0  34.215148
274  28.00  6.55  7.000    7.000    7.6000          91000.0  31.974597
275  27.00  6.75  7.900    1.150    3.3500          27390.0  36.837514
276  26.00  6.95  8.100    1.000    2.7000            651.0  38.050302
277  26.50  7.90  8.100    1.350    0.7500           2701.0  40.458857
278  26.00  7.50  7.850    0.950    0.5500            765.0  37.636063
279  26.50  7.50  7.900    1.350    0.6500           4601.0  38.226242

In [31]:
import math

In [53]:
map_do = {(0,5):[2,5],(5,10):[5,7],(10,15):[7,10],(15,20):[5,7],(15,20):[10,12],
           (20,25):[12,15],(25,30):[15,19],(30,35):[19,23],
           (35,40):[23,30],(40,45):[30,37],(45,50):[37,44],
           (50,55):[44,51],(55,60):[51,57],(60,65):[57,66],
           (65,70):[66,75],(70,75):[75,81],
           (75,80):[81,87],(80,85):[87,91],
           (85,90):[91,95],(90,95):[95,98],
           (95,100):[98,99],(100,105):[99,98],
           (105,110):[98,96],(110,115):[96,93],
           (115,120):[93,90],(120,125):[90,87],
           (125,130):[87,84],(130,135):[84,81],
           (135,140):[81,78]}

def q_do(val):
  if val > 140:
    return 50
  for range in map_do:
    if val == range[0]:
      return map_do[range][0]
    elif val == range[1]:
      return map_do[range][1]
    elif  range[0] < val < range[1]:
      diff = (map_do[range][1] - map_do[range][0])/(range[1]-range[0])
      res =  map_do[range][0] + diff * (val - range[0])
      return res
print(q_do(9))

6.6

In [34]:
map_ph = {(2.2,2.4):[2,3],(2.4,2.6):[3,3],(2.6,2.8):[3,4],
          (2.8,3):[4,4],(3,3.2):[4,5],(3.2,3.4):[5,6],
          (3.4,3.6):[6,7],(3.6,3.8):[7,8],(3.8,4):[8,9],
          (4,4.2):[9,11],(4.2,4.4):[11,14],(4.4,4.6):[14,17],
          (4.6,4.8):[17,20],(4.8,5):[20,27],(5,5.2):[27,33],
          (5.2,5.4):[33,38],(5.4,5.6):[38,44],(5.6,5.8):[44,49],
          (5.8,6):[49,55],(6,6.2):[55,60],(6.2,6.4):[60,68],
          (6.4,6.6):[68,75],(6.6,6.8):[75,83],(6.8,7):[83,88],
          (7,7.2):[88,92],(7.2,7.4):[92,92],(7.4,7.6):[92,92],
          (7.6,7.8):[92,90],(7.8,8):[90,84],(8,8.2):[84,77],
          (8.2,8.4):[77,70],(8.4,8.6):[70,63],(8.6,8.8):[63,56],
          (8.8,9):[56,49],(9,9.2):[49,42],(9.2,9.4):[42,36],
          (9.4,9.6):[36,29],(9.6,9.8):[29,24],(9.8,10):[24,20],
          (10,10.2):[20,17],(10.2,10.4):[17,14],(10.4,10.6):[14,12],
          (10.6,10.8):[12,10],(10.8,11):[10,8],(11,11.2):[8,7],
          (11.2,11.4):[7,6],(11.4,11.6):[6,5],(11.6,11.8):[5,4],
          (11.8,12):[4,3]}

def q_ph(val):
  if val < 2 or val > 12:
    return 0
  for range in map_ph:
    if val == range[0]:
      return map_ph[range][0]
    elif val == range[1]:
      return map_ph[range][1]
    elif range[0] < val < range[1]:
      diff = (map_ph[range][1]-map_ph[range][0]) / (range[1]-range[0])
      return map_ph[range][0]+diff*(val-range[0])

In [54]:
map_bod = {(0,1):[100,95],(1,2):[95,80],(2,3):[80,67],
            (3,4):[67,61],(4,5):[61,56],(5,6):[56,51],
            (6,7):[51,46],(7,8):[46,42],(8,9):[42,38],
            (9,10):[38,34],(10,11):[34,30],(11,12):[30,28],(12,13):[28,25],
            (13,14):[25,23],(14,15):[23,20],(15,16):[20,18],(16,17):[18,16],
            (17,18):[16,14],(18,19):[14,13],(19,20):[13,12],
            (20,21):[12,11],(21,22):[11,10],(22,23):[10,9],(23,24):[9,8],
            (24,25):[8,7],(25,26):[7,7],(26,27):[7,6],(27,28):[6,6],
            (28,29):[6,5],(29,30):[5,5]
            }
def q_bod(val):
  if val > 30:
    return 2
  for range in map_bod:
    if val == range[0]:
      return map_bod[range][0]
    elif val == range[1]:
      return map_bod[range][1]
    elif range[0] < val < range[1]:
      diff = (map_bod[range][1]-map_bod[range][0]) / (range[1]-range[0])
      return map_bod[range][0]+diff*(val-range[0])
      [range][0]+diff*(val-range[0])
print(q_bod(2.5))

73.5

In [38]:
map_faecal = {(1,2):[99,91],(2,3):[91,86],(3,4):[86,82],(4,5):[82,80],
              (5,6):[80,78],(6,7):[78,76],(7,8):[76,74],(8,9):[74,73],
              (9,10):[73,72],(10,20):[72,63],(20,30):[63,58],(30,40):[58,55],
              (40,50):[55,52],(50,60):[52,50],(60,70):[50,48],(70,80):[48,47],
              (80,90):[47,45],(90,100):[45,44],(100,200):[44,37],(200,300):[37,34],
              (300,400):[34,31],(400,500):[31,29],(500,600):[29,27],(600,700):[27,25],
              (700,800):[25,24],(800,900):[24,23],(900,1000):[23,22],(1000,2000):[22,18],
              (2000,3000):[18,16],(3000,4000):[16,15],(4000,5000):[15,14],
              (5000,6000):[14,13],(6000,7000):[13,12],(7000,8000):[12,11],(8000,9000):[11,11],
              (9000,10000):[11,10],(10000,20000):[10,8],(20000,30000):[8,7],
              (30000,40000):[7,6],(40000,50000):[6,6],(50000,60000):[6,5],
              (60000,70000):[5,5],(70000,80000):[5,5],(80000,90000):[5,4],
              (90000,100000):[4,4]
              }

def q_faecal(val):
  if val > 100000:
    return 2
  for range in map_faecal:
    if val == range[0]:
      return map_faecal[range][0]
    elif val == range[1]:
      return map_faecal[range][1]
    elif range[0] < val < range[1]:
      diff = (map_faecal[range][1]-map_faecal[range][0]) / (range[1]-range[0])
      return map_faecal[range][0]+diff*(val-range[0])
# print(q_faecal(2))

In [86]:
map_nitrate = {(0,1):[97,96],(1,2):[96,95],(2,3):[95,90],(3,4):[90,70],
               (4,5):[70,65],(5,6):[65,60],(6,7):[60,58],(7,8):[58,56],
               (8,9):[56,53],(9,10):[53,51],(10,12):[51,48],(12,14):[48,45],
               (14,16):[45,42],(16,18):[42,39],(18,20):[39,37],(20,22):[37,35],
               (22,24):[35,33],(24,26):[33,31],(26,28):[31,29],(28,30):[29,27],
               (30,32):[27,25],(32,34):[25,23],(34,36):[23,21],(36,38):[21,19],
               (38,40):[19,18],(40,42):[18,16],(42,44):[16,15],(44,46):[15,13],
               (46,48):[13,12],(48,50):[12,10],(50,52):[10,9],(52,54):[9,8],
               (54,56):[8,8],(56,58):[8,7],(58,60):[7,7],(60,62):[7,6],
               (62,64):[6,6],(64,66):[6,6],(66,68):[6,5],(68,70):[5,5],
               (70,80):[5,4],(80,90):[4,3],(90,100):[3,3]
}
def q_nitrate(val):
  if val > 100:
    return 1
  for range in map_nitrate:
    if val == range[0]:
      return map_nitrate[range][0]
    elif val == range[1]:
      return map_nitrate[range][1]
    elif range[0] < val < range[1]:
      diff = (map_nitrate[range][1]-map_nitrate[range][0]) / (range[1]-range[0])
      return map_nitrate[range][0]+diff*(val-range[0])

# print(q_nitrate(101))

1

In [65]:
dict={}
for i in range(-10,30):
  dict[(i,i+1)]=[]

In [88]:
map_temp={(-10, -9): [55,59],
 (-9, -8): [59,63],
 (-8, -7): [63,66],
 (-7, -6): [66,70],
 (-6, -5): [70,74],
 (-5, -4): [74,78],
 (-4, -3): [78,82],
 (-3, -2): [82,85],
 (-2, -1): [85,89],
 (-1, 0): [89,93],
 (0, 1): [93,89],
 (1, 2): [89,85],
 (2, 3): [85,81],
 (3, 4): [81,77],
 (4, 5): [77,73],
 (5, 6): [73,67],
 (6, 7): [67,61],
 (7, 8): [61,56],
 (8, 9): [56,50],
 (9, 10): [50,45],
 (10, 11): [45,40],
 (11, 12): [40,36],
 (12, 13): [36,34],
 (13, 14): [34,33],
 (14, 15): [33,31],
 (15, 16): [31,29],
 (16, 17): [29,27],
 (17, 18): [27,26],
 (18, 19): [26,24],
 (19, 20): [24,22],
 (20, 21): [22,20],
 (21, 22): [20,19],
 (22, 23): [19,18],
 (23, 24): [18,17],
 (24, 25): [17,16],
 (25, 26): [16,14],
 (26, 27): [14,13],
 (27, 28): [13,12],
 (28, 29): [12,11],
 (29, 30): [11,10],}



def q_temp(val):
  if val > 30:
    return 10
  if val < -10:
    return 55
  for range in map_temp:
    if val == range[0]:
      return map_temp[range][0]
    elif val == range[1]:
      return map_temp[range][1]
    elif range[0] < val < range[1]:
      diff = (map_temp[range][1]-map_temp[range][0]) / (range[1]-range[0])
      return map_temp[range][0]+diff*(val-range[0])

print(q_temp(-11))

55